<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Seeder;

class UserTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'family' => 'Иванов',
                'name' => 'Иван',
                'patronymic' => 'Иванович',
                'email' => 'ivanov@mail.ru',
                'login' => 'admin',
                'password' => Hash::make('admin'),
                'role_id' => '0',
            ],
            [
                'family' => 'Иванов',
                'name' => 'Александр',
                'patronymic' => 'Сергеевич',
                'email' => 'alexander_ivanov@yandex.ru',
                'login' => 'ivan_alex',
                'password' => Hash::make('AlexS_Iva1213'),
                'role_id' => '1',
                ],
                [
                'family' => 'Смирнова',
                'name' => 'Елена',
                'patronymic' => 'Владимировна',
                'email' => 'elenasmirnova2005@mail.ru',
                'login' => 'elenasmirnova',
                'password' => Hash::make('ES11_Smirnova'),
                'role_id' => '1',
                ],
                [
                'family' => 'Васильев',
                'name' => 'Константин',
                'patronymic' => 'Николаевич',
                'email' => 'konstantin_vasiliev@mail.ru',
                'login' => 'vasil_konst',
                'password' => Hash::make('KonVasiliev32'),
                'role_id' => '1',
                ],
                [
                'family' => 'Белова',
                'name' => 'Мария',
                'patronymic' => 'Сергеевна',
                'email' => 'maria_belova@gmail.com',
                'login' => 'mbelova',
                'password' => Hash::make('MBelova_07'),
                'role_id' => '1',
                ],
                [
                'family' => 'Морозов',
                'name' => 'Сергей',
                'patronymic' => 'Иванович',
                'email' => 'si_morozov@gmail.com',
                'login' => 'moroz_si',
                'password' => Hash::make('Morozov_IS'),
                'role_id' => '1',
                ],
                [
                'family' => 'Громова',
                'name' => 'Анна',
                'patronymic' => 'Ивановна',
                'email' => 'gromova_anna@yandex.ru',
                'login' => 'annagromova',
                'password' => Hash::make('AGromova_19'),
                'role_id' => '1',
                ],
                [
                'family' => 'Орлова',
                'name' => 'Татьяна',
                'patronymic' => 'Викторовна',
                'email' => 'tatyana_orlova@gmail.com',
                'login' => 'tatiana_orlova',
                'password' => Hash::make('TOrlova_63'),
                'role_id' => '1',
                ],
                [
                'family' => 'Яковлев',
                'name' => 'Борис',
                'patronymic' => 'Сергеевич',
                'email' => 'boris_yakovlev@mail.ru',
                'login' => 'boryak',
                'password' => Hash::make('BYakovlev'),
                'role_id' => '1',
                ],
                [
                'family' => 'Кузнецов',
                'name' => 'Николай',
                'patronymic' => 'Петрович',
                'email' => 'nikolai_kuznetsov@yandex.ru',
                'login' => 'nkuznetsov',
                'password' => Hash::make('NKuznetsov_95'),
                'role_id' => '1',
                ],
                [
                'family' => 'Полякова',
                'name' => 'Александра',
                'patronymic' => 'Евгеньевна',
                'email' => 'aleksandra_polyakova@gmail.com',
                'login' => 'poly_a',
                'password' => Hash::make('APolya_16'),
                'role_id' => '1',
                ],
                [
                'family' => 'Алексеев',
                'name' => 'Роман',
                'patronymic' => 'Геннадьевич',
                'email' => 'roman_alekseev@company.com',
                'login' => 'ralekseev',
                'password' => Hash::make('RAlekseev_68'),
                'role_id' => '1',
                ],
                [
                'family' => 'Борисова',
                'name' => 'Ольга',
                'patronymic' => 'Викторовна',
                'email' => 'borisova_olga@gmail.com',
                'login' => 'oborisova',
                'password' => Hash::make('OBorisova_23'),
                'role_id' => '1',
                ],
                [
                'family' => 'Попов',
                'name' => 'Игорь',
                'patronymic' => 'Сергеевич',
                'email' => 'igor_popov@gmail.com',
                'login' => 'igorp',
                'password' => Hash::make('IPopov_94'),
                'role_id' => '1',
                ],
                [
                'family' => 'Киселёва',
                'name' => 'Екатерина',
                'patronymic' => 'Владимировна',
                'email' => 'ekaterina_kiseleva@mail.ru',
                'login' => 'katya_kiss',
                'password' => Hash::make('EKissKiseleva_01'),
                'role_id' => '1',
                ],
                [
                'family' => 'Егоров',
                'name' => 'Семён',
                'patronymic' => 'Александрович',
                'email' => 'sa_egorov@mail.ru',
                'login' => 'semeg_orov',
                'password' => Hash::make('SAEgorov_56'),
                'role_id' => '1',
                ],
                [
                'family' => 'Акашкин',
                'name' => 'Святослав',
                'patronymic' => 'Алексеевич',
                'email' => 'akash18@gmail.com',
                'login' => 'svatoslav',
                'password' => Hash::make('akasvTR188'),
                'role_id' => '2',
                ],
                [
                'family' => 'Елисеев',
                'name' => 'Кирилл',
                'patronymic' => 'Вячеславович',
                'email' => 'eliseevkir@mail.com',
                'login' => 'kirilll4',
                'password' => Hash::make('apple45tr'),
                'role_id' => '2',
                ],
                [
                'family' => 'Бебишева',
                'name' => 'Валентина',
                'patronymic' => 'Петровна',
                'email' => 'bebishevaval@gmail.com',
                'login' => 'bebval_34',
                'password' => Hash::make('bebval89456'),
                'role_id' => '2',
                ],
                [
                'family' => 'Белов',
                'name' => 'Василий',
                'patronymic' => 'Дмитриевич',
                'email' => 'belov_dm@gmail.com',
                'login' => 'vasjabel',
                'password' => Hash::make('g7d99ds76'),
                'role_id' => '2',
                ],
                [
                'family' => 'Володина',
                'name' => 'Ирина',
                'patronymic' => 'Александровна',
                'email' => 'volod_iriA@gmail.com',
                'login' => 'AI_irina',
                'password' => Hash::make('volodina890'),
                'role_id' => '2',
                ],
                [
                'family' => 'Елисеев',
                'name' => 'Евгений',
                'patronymic' => 'Владимирович',
                'email' => 'eliseevevgen@gmail.com',
                'login' => 'eliseedy',
                'password' => Hash::make('good675TR'),
                'role_id' => '2',
                ],
                [
                'family' => 'Кашаев',
                'name' => 'Роман',
                'patronymic' => 'Сергеевич',
                'email' => 'kashaev_roman@gmail.com',
                'login' => 'romaES',
                'password' => Hash::make('rokash6547'),
                'role_id' => '2',
                ],
                [
                'family' => 'Киселёв',
                'name' => 'Евгений',
                'patronymic' => 'Алексеевич',
                'email' => 'kiselevaleks@gmail.com',
                'login' => 'kiselevEVGEN',
                'password' => Hash::make('evgeniy765'),
                'role_id' => '2',
                ],
                [
                'family' => 'Кинякин',
                'name' => 'Николай',
                'patronymic' => 'Александрович',
                'email' => 'kinjakinnikola@gmail.com',
                'login' => 'MS_nikola',
                'password' => Hash::make('hook56_dum'),
                'role_id' => '2',
                ],
                [
                'family' => 'Лукьянов',
                'name' => 'Андрей',
                'patronymic' => 'Васильевич',
                'email' => 'lykjanov_andr@gmail.com',
                'login' => 'lykjanov_A',
                'password' => Hash::make('andrei7000'),
                'role_id' => '2',
                ],
                [
                'family' => 'Молотков',
                'name' => 'Дмитрий',
                'patronymic' => 'Алексеевич',
                'email' => 'molotkov@gmail.com',
                'login' => 'dima_molot',
                'password' => Hash::make('molotkov_d_98'),
                'role_id' => '2',
                ],
                [
                'family' => 'Москвичев',
                'name' => 'Сергей',
                'patronymic' => 'Андреевич',
                'email' => 'moskvichevSER@gmail.com',
                'login' => 'moskvich',
                'password' => Hash::make('sermos45'),
                'role_id' => '2',
                ],
                [
                'family' => 'Мурзаев',
                'name' => 'Николай',
                'patronymic' => 'Николаевич',
                'email' => 'myrzaevnini@gmail.com',
                'login' => 'NiKol34',
                'password' => Hash::make('nhnhgh5'),
                'role_id' => '2',
                ],
                [
                'family' => 'Нуштаев',
                'name' => 'Эдуард',
                'patronymic' => 'Юрьевич',
                'email' => 'eduardnush@gmail.com',
                'login' => 'edik17',
                'password' => Hash::make('dfjxi56'),
                'role_id' => '2',
                ],
                [
                'family' => 'Панькин',
                'name' => 'Иван',
                'patronymic' => 'Иванович',
                'email' => 'pankinivanP@gmail.com',
                'login' => 'ivaaanPAnkin',
                'password' => Hash::make('fdu_543'),
                'role_id' => '2',
                ],
                [
                'family' => 'Пизелев',
                'name' => 'Николай',
                'patronymic' => 'Александрович',
                'email' => 'piselevNIK@gmail.com',
                'login' => 'kolya',
                'password' => Hash::make('pis758elv'),
                'role_id' => '2',
                ],
                [
                'family' => 'Ромашкин',
                'name' => 'Александр',
                'patronymic' => 'Николаевич',
                'email' => 'romshkinALEX@gmail.com',
                'login' => 'nikolaevich',
                'password' => Hash::make('gfhf676g'),
                'role_id' => '2',
                ],
                [
                'family' => 'Трунькина',
                'name' => 'Екатерина',
                'patronymic' => 'Дмитриевна',
                'email' => 'trynkina@gmail.com',
                'login' => 'ekaterina',
                'password' => Hash::make('katja56tdf'),
                'role_id' => '2',
                ],
                [
                'family' => 'Фролов',
                'name' => 'Илья',
                'patronymic' => 'Дмитриевич',
                'email' => 'ilyafrolov@gmail.com',
                'login' => 'ilya456',
                'password' => Hash::make('ilya_fr7'),
                'role_id' => '2',
                ],
                [
                'family' => 'Шалаев',
                'name' => 'Дмитрий',
                'patronymic' => 'Сергеевич',
                'email' => 'schalaev_dimon@gmail.com',
                'login' => 'shalaevDI',
                'password' => Hash::make('dimas765'),
                'role_id' => '2',
                ],
                [
                'family' => 'Горбунова',
                'name' => 'Мария',
                'patronymic' => 'Александровна',
                'email' => 'gorbynovaMARIA@gmail.com',
                'login' => 'masha_000',
                'password' => Hash::make('masha4786'),
                'role_id' => '2',
                ],
                [
                'family' => 'Ермикина',
                'name' => 'Вероника',
                'patronymic' => 'Андреевна',
                'email' => 'ermikinaVEROn@gmail.com',
                'login' => 'veronikaEr',
                'password' => Hash::make('ermikinaveronika$'),
                'role_id' => '2',
                ],
                [
                'family' => 'Катаева',
                'name' => 'Виктория',
                'patronymic' => 'Сергеевна',
                'email' => 'kataevavika@gmail.com',
                'login' => 'vika_kataeva',
                'password' => Hash::make('viktoria7778'),
                'role_id' => '2',
                ],
                [
                'family' => 'Кирдяшкина',
                'name' => 'Валерия',
                'patronymic' => 'Александровна',
                'email' => 'kirdjashkinaVALERIA@gmail.com',
                'login' => 'lera_kird',
                'password' => Hash::make('kiraR'),
                'role_id' => '2',
                ],
                [
                'family' => 'Ковайкина',
                'name' => 'Василиса',
                'patronymic' => 'Алексеевна',
                'email' => 'kovajkinaVASILISA@gmail.com',
                'login' => 'vasilisaKOV',
                'password' => Hash::make('dym789T'),
                'role_id' => '2',
                ],
                
        ]);        
    }
}
